apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: yasoja44/node-app:v1
          ports:
            - containerPort: 5000
              name: nodejs-port
  selector:
    matchLabels:
      app: server
      
---

apiVersion: v1
kind: Service
metadata:
  name: cloudl-server-service
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: server
  type: ClusterIP
      
